### ISSUE TITLE
LiVi Image output with textures

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#31] opened 2021-07-05 14:28 UTC
Hi @rgsouthall,

I am trying to get the output of the LiVi Image node but it seems that it doesn't render the texture of the scene structures. For example below is the output from blender's and LiVi's rendering engines respectively:

![image-1__hdr_](https://user-images.githubusercontent.com/10189018/124486111-8d9eb000-ddad-11eb-93a5-2d102d31aee6.png) 
![image-1__hdr_preview_medium](https://user-images.githubusercontent.com/10189018/124486132-93949100-ddad-11eb-9ba1-465cd2b1bd18.png)

so as you can see in the second rendering the textures are missing. The node settings that I am using are the following:

![image](https://user-images.githubusercontent.com/10189018/124486414-dc4c4a00-ddad-11eb-916f-db14cbb6d655.png)

any idea what I might be missing?

Thanks.

**Comment by rgsouthall** [comment] 2021-07-05 14:47
You have illuminance turned on which makes Radiance convert all initial
bounce materials to white diffuse.

**Comment by ttsesm** [comment] 2021-07-05 14:57
Hhmm, well if I turn off the illuminance option this is what I am getting:

![image-1__hdr_illuminance_off](https://user-images.githubusercontent.com/10189018/124490001-e53f1a80-ddb1-11eb-9a66-c7eb22b80826.png)

which still does not render textures and also my scene seems to be darker.

**Comment by ttsesm** [comment] 2021-07-06 08:17
Hi @rgsouthall, any idea or something else I could try?

**Comment by rgsouthall** [comment] 2021-07-06 17:33
Assuming you have followed the instructions in the manual for Radiance Patterns & Textures then I don't know.

**Comment by ttsesm** [comment] 2021-07-07 10:27
> Assuming you have followed the instructions in the manual for Radiance Patterns & Textures then I don't know.

I just use the default options set from the Vi-Suite. I do not use any custom command, parameters or whatever.

Just a favor to get out of curiosity, can you render the LiVi Image in your set up from the file in the link bellow (it is a wetranfer link, for some reason github wasn't allow me to attach the .blend file in a zipped format) and check whether you are getting the same output or not. Everything should be embedded (textures, Vi-node network) and it should work out of the box.

https://we.tl/t-NYJQbjbX31

Thanks.

**Comment by rgsouthall** [comment] 2021-07-07 12:02
Well if you don't do "whatever" the user manual says to get it to work it's unlikely to. Whoever told you it "should" work without following the user manual instructions was mistaken.
Closing this is as it's not a bug report.

**Closed as completed by rgsouthall** 2021-07-07 12:02 UTC

**Comment by ttsesm** [comment] 2021-07-08 12:00
Hi Ryan,

Well I've never said that there is a bug. My question derives from the fact that I've used the steps described in [Radiance Patterns](https://www.youtube.com/watch?v=0RXTu-brBZI) and [Radiance Textures](https://www.youtube.com/watch?v=K_nloppSRlg) from your tutorials but still I do not get the correct output.

**Comment by ttsesm** [comment] 2021-07-12 14:04
Hi @rgsouthall,

I've created a small test case scene and followed all the steps described in the `Radiance Patterns` video but still as you can see the LiVi image preview is not showing the texture:
![image](https://user-images.githubusercontent.com/10189018/125301303-2348bb00-e32b-11eb-8a5b-fb5341849e96.png)


 Thus, I am not sure whether I am still doing something wrong from my side.
